import Head from 'next/head'
import SearchPage from "./SearchPage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sahara - Google for web3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchPage />
    </div>
  )
}
